sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: sgny0128@
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tF8g8VTyWdXRj7X9nfE
    access-key-secret: qFfiGOg8LP1FZ52ADpPGT89x3l7F1h
    bucket-name: shgny
  redis:
    host: localhost
    port: 6379
    password: sgny0128@
    database: 0
  wechat:
    appid: wx601135b68bc0c406
    secret: 321104ace7f74dce6a8258c1636a3ed4
