sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: password
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: access-key-id
    access-key-secret: access-key-secret
    bucket-name: bucket-name
  redis:
    host: localhost
    port: 6379
    password: password
    database: 0
  wechat:
    appid: appid
    secret: secret
  baidu:
    AK: AK
  shop:
    address: 北京市海淀区上地十街10号
